name: Lighthouse CI
on: deployment_status

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Lighthouse CI
        run: npx lhci autorun --url=${{ github.event.deployment_status.target_url }}
