name: Lighthouse CI
on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Run Lighthouse CI
        run: |
          PORT=$(npm run preview & sleep 2 && lsof -i -P | grep LISTEN | grep node | awk '{print $9}' | cut -d ':' -f2) && \
          npx lhci autorun \
            --collect.startServerCommand="npm run preview" \
            --collect.url="http://localhost:$PORT"
