name: Lighthouse CI
on: deployment_status

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Lighthouse CI
        run: |
          if [ -z "${{ github.event.deployment_status.target_url }}" ]; then
            echo "Error: No deployment URL found"
            exit 1
          fi
          npx lhci autorun --collect.url=${{ github.event.deployment_status.target_url }} --collect.staticDistDir=./
