name: Lighthouse CI
on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Run Lighthouse CI
        run: |
          npm run preview & sleep 5 && \
          npx lhci autorun \
            --collect.startServerCommand="npm run preview" \
            --collect.url=http://localhost:5173
